# Generated by Django 4.2 on 2023-04-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_rename_title_category_song_album_alter_song_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-updated', 'created']},
        ),
    ]
