# Generated by Django 4.2 on 2023-04-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_album_song_category_alter_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.category'),
        ),
    ]
